# Generated by Django 2.2.4 on 2020-07-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_x', models.DecimalField(decimal_places=20, max_digits=22)),
                ('acc_y', models.DecimalField(decimal_places=20, max_digits=22)),
                ('acc_z', models.DecimalField(decimal_places=20, max_digits=22)),
                ('gyr_x', models.DecimalField(decimal_places=20, max_digits=22)),
                ('gyr_y', models.DecimalField(decimal_places=20, max_digits=22)),
                ('gyr_z', models.DecimalField(decimal_places=20, max_digits=22)),
                ('fecha', models.CharField(max_length=25)),
                ('hora', models.CharField(max_length=25)),
                ('anomalia', models.BooleanField(default=False)),
            ],
        ),
    ]
